#!/usr/bin/env python3
"""Generate a radar TX packet for a SYNC length and PSDU choice.

SYNC: 32, 64, 128, 256, 512, 1024, 2048.
PSDU:
  default           0 bytes (PSDULength=0, no MAC payload)
  --psdu-bytes N    N random data bytes + IEEE 802.15.4 FCS (unless
                    --no-fcs).  N=0 is the default empty PSDU.
  --psdu-hex HEX    exact PSDU bytes (no extra FCS)

Waveforms are generated by MATLAB export_uwb_radar_packet.m (Communications
Toolbox lrwpanWaveformGenerator).  BPRF native PreambleDuration is
16/64/1024/4096; other SYNC lengths crop/tile the pulse-shaped SYNC field.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys

ALLOWED_SYNC = (32, 64, 128, 256, 512, 1024, 2048)
HERE = os.path.dirname(os.path.abspath(__file__))
MATLAB_EXPORT = os.path.join(HERE, "export_uwb_radar_packet.m")


def find_matlab():
    env = os.environ.get("MATLAB") or os.environ.get("MATLAB_BIN")
    if env and os.path.isfile(env):
        return env
    for c in (
        "/mnt/f/MATLAB/bin/matlab.exe",
        "/mnt/f/MATLAB/bin/matlab",
        shutil.which("matlab"),
    ):
        if c and os.path.isfile(c):
            return c
    return None


def matlab_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def build_matlab_call(out_dir, sync, psdu_bytes, psdu_hex, seed, append_fcs):
    args = [matlab_quote(os.path.abspath(out_dir)), str(int(sync))]
    nv = ["'RandomSeed'", str(int(seed)), "'AppendFCS'",
          "true" if append_fcs else "false"]
    if psdu_hex:
        nv += ["'PSDUHex'", matlab_quote(psdu_hex)]
    else:
        nv += ["'PSDUBytes'", str(int(psdu_bytes))]
    return "export_uwb_radar_packet(%s, %s)" % (
        ", ".join(args), ", ".join(nv))


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--sync-reps", type=int, default=64, choices=ALLOWED_SYNC)
    p.add_argument("--psdu-bytes", type=int, default=0,
                   help="random data-byte count (default 0 = empty PSDU)")
    p.add_argument("--psdu-hex", default="",
                   help="exact PSDU hex; overrides --psdu-bytes")
    p.add_argument("--psdu-random-seed", type=int, default=20260904)
    p.add_argument("--no-fcs", action="store_true",
                   help="do not append IEEE FCS when using --psdu-bytes > 0")
    p.add_argument("--out-dir", required=True)
    p.add_argument("--matlab", default="")
    args = p.parse_args(argv)

    if args.psdu_bytes < 0:
        p.error("--psdu-bytes must be >= 0")
    hex_digits = "".join(c for c in args.psdu_hex if c in "0123456789abcdefABCDEF")
    if args.psdu_hex and len(hex_digits) % 2 != 0:
        p.error("--psdu-hex must have an even number of hex digits")
    psdu_len = (len(hex_digits) // 2) if args.psdu_hex else (
        0 if args.psdu_bytes == 0 else
        args.psdu_bytes + (0 if args.no_fcs else 2))
    if psdu_len > 127:
        p.error("PSDULength %d exceeds 127" % psdu_len)

    matlab = args.matlab or find_matlab()
    if not matlab:
        print("MATLAB not found; set --matlab or MATLAB_BIN. "
              "Cannot synthesize PHR/PSDU without lrwpanWaveformGenerator.",
              file=sys.stderr)
        return 2

    os.makedirs(args.out_dir, exist_ok=True)
    cmd = build_matlab_call(args.out_dir, args.sync_reps, args.psdu_bytes,
                            hex_digits, args.psdu_random_seed, not args.no_fcs)
    # cd to testdata/uwb_radar so export_uwb_radar_packet is on the path.
    batch = "cd(%s); %s;" % (matlab_quote(HERE), cmd)
    print("MATLAB:", matlab)
    print("batch:", batch)
    r = subprocess.run([matlab, "-batch", batch], check=False)
    return r.returncode


if __name__ == "__main__":
    sys.exit(main())
