/* -*- c++ -*- */
/*
 * Copyright 2026
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * M1-B unit QA (Agent D) against ONE `EndpointCore`.
 *
 * Every expectation here is either an invariant stated by `uwb_twr_core.h` /
 * `uwb_twr_protocol_time.h` or a hand-computed / Python-`fractions`-derived
 * value recorded in testdata/twr/m1b/.  Nothing is generated by running the
 * FSM or the formula.
 *
 * B-ID coverage that lives in this file: B04, B05, B06, B07, B08, B09, B10,
 * B11, B12, B13, B14, B15, B16 (structural + causal), plus the ratio half of
 * B02.  The four-direction B01 cells and the network-level B03 drops are in
 * qa_uwb_twr_m1b_e2e.cc.
 */

#include <gnuradio/uwb/uwb_twr_core.h>
#include <gnuradio/uwb/uwb_twr_fake_link.h>
#include <gnuradio/uwb/uwb_twr_frame.h>

#include "twr_m1b_test_support.h"

#include <boost/test/unit_test.hpp>

#include <cstdint>
#include <string>
#include <type_traits>
#include <vector>

using namespace gr::uwb::twr;
using namespace gr::uwb::twr::m1b_test;

// Boost.Test prints failed comparisons with `operator<<`.  These are defined in
// the types' own namespace so ADL finds them, without touching the production
// headers.
namespace gr {
namespace uwb {
namespace twr {
inline std::ostream& operator<<(std::ostream& os, TofStatus s)
{
    return os << tof_status_to_string(s);
}
inline std::ostream& operator<<(std::ostream& os, ExchangeStatus s)
{
    return os << exchange_status_to_string(s);
}
inline std::ostream& operator<<(std::ostream& os, ProtocolCompletionStatus s)
{
    return os << protocol_completion_status_to_string(s);
}
inline std::ostream& operator<<(std::ostream& os, FrameType t)
{
    return os << frame_type_to_string(t);
}
inline std::ostream& operator<<(std::ostream& os, EndpointState s)
{
    return os << endpoint_state_to_string(s);
}
inline std::ostream& operator<<(std::ostream& os, AdapterFault f)
{
    return os << adapter_fault_to_string(f);
}
inline std::ostream& operator<<(std::ostream& os, Protocol p)
{
    return os << protocol_to_string(p);
}
inline std::ostream& operator<<(std::ostream& os, Role r) { return os << role_to_string(r); }
inline std::ostream& operator<<(std::ostream& os, PeerClaimError e)
{
    return os << peer_claim_error_to_string(e);
}
inline std::ostream& operator<<(std::ostream& os, TimestampField f)
{
    return os << timestamp_field_name(f);
}
inline std::ostream& operator<<(std::ostream& os, FrameMatch m)
{
    return os << frame_match_to_string(m);
}
namespace detail {
inline std::ostream& operator<<(std::ostream& os, KernelStatus s)
{
    switch (s) {
    case KernelStatus::Ok:
        return os << "ok";
    case KernelStatus::Overflow:
        return os << "overflow";
    case KernelStatus::ZeroDenominator:
        return os << "zero_denominator";
    }
    return os << "invalid";
}
} // namespace detail
} // namespace twr
} // namespace uwb
} // namespace gr

namespace {

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

struct Env {
    ClockDomain dom;
    FrameProfile prof;
    CalibrationStamp cal;
    CoreConfig cfg;
};

Env make_env(Role role,
             Protocol proto,
             uint16_t modulus = 4,
             uint16_t initial = 0,
             uint32_t result_cap = 8,
             int64_t exchange_timeout = 100000)
{
    Env e;
    e.dom = make_domain("x410_test_dev", 1.0e9, 1, 40);
    e.prof = make_profile(1.0e9);
    e.cal = make_calibration("cal1", 1, 0, 1000000000LL);

    CoreConfig& c = e.cfg;
    c.endpoint_id = (role == Role::Initiator) ? "A" : "B";
    c.protocol = proto;
    c.role = role;
    c.pan_id = 0x1234;
    c.local_address = (role == Role::Initiator) ? 0x0101 : 0x0202;
    c.peer_address = (role == Role::Initiator) ? 0x0202 : 0x0101;
    c.session_id = 7;
    c.session_generation = 1;
    c.sequence_modulus = modulus;
    c.initial_sequence = initial;
    c.local_domain = e.dom;
    c.peer_binding = make_binding(e.dom, 1, 1, 1000000, modulus);
    ClockRatio::unity_same_clock(e.dom, c.ratio);
    c.frame_profile = e.prof;
    c.local_calibration = e.cal;
    c.exchange_timeout_ticks = exchange_timeout;
    c.evidence_wait_ticks = exchange_timeout;
    c.result_queue_capacity = result_cap;
    c.max_in_flight = 1;
    return e;
}

const CoreAction* find_action(const CoreActionBatch& b, CoreActionKind k)
{
    for (size_t i = 0; i < b.count; ++i) {
        if (b.actions[i].kind == k)
            return &b.actions[i];
    }
    return nullptr;
}

bool has_action(const CoreActionBatch& b, CoreActionKind k)
{
    return find_action(b, k) != nullptr;
}

Frame base_frame(const CoreConfig& cfg, FrameType t, uint16_t seq)
{
    Frame f;
    f.version = cfg.frame_profile.version;
    f.function_code = t;
    f.session_id = cfg.session_id;
    f.seq = seq;
    f.pan_id = cfg.pan_id;
    f.src_addr = cfg.peer_address;
    f.dst_addr = cfg.local_address;
    f.flags = make_flags(true, false);
    return f;
}

CoreEvent rx_of(const CoreConfig& cfg,
                const Frame& f,
                int64_t ticks,
                const ClockDomain& d,
                FirstPathQuality fp = FirstPathQuality::passed(20.0, 6.0, 0.9))
{
    CoreEvent e;
    e.kind = CoreEventKind::RxFrame;
    e.fcs_passed = true;
    e.decode_ok = true;
    e.frame = f;
    e.rx_time = make_rx_ts(ticks, d, cfg.local_calibration.id);
    e.rx_first_path = fp;
    return e;
}

CoreEvent make_accepted(const TxToken& t, uint64_t event_id = 0)
{
    CoreEvent e;
    e.kind = CoreEventKind::TxAccepted;
    e.event_id = event_id;
    e.token = t;
    return e;
}

CoreEvent outcome_ev(const TxToken& t,
                     TxOutcome o,
                     AdapterFault f = AdapterFault::None,
                     uint64_t event_id = 0)
{
    CoreEvent e;
    e.kind = CoreEventKind::TxOutcomeResolved;
    e.event_id = event_id;
    e.token = t;
    e.tx_outcome = o;
    e.adapter_fault = f;
    return e;
}

// The product action carries a strong `ProtocolTerminalStatus` (F's review
// finding B-1).  This TEST helper maps it back onto the exchange vocabulary the
// stored expectations use; the product API no longer exposes a status that
// `exchange_status_yields_range()` accepts.
inline ExchangeStatus action_status(const CoreAction& a)
{
    ExchangeStatus r = ExchangeStatus::InternalError;
    if (a.status.failure_reason(r))
        return r;
    if (a.status.completion == ProtocolCompletionStatus::Complete)
        return ExchangeStatus::Ok;
    return ExchangeStatus::InternalError;
}

// The protocol estimate exposes its failure reason only through a failed-only
// accessor (F's finding N-10); this TEST helper reads it for the assertions.
inline ExchangeStatus est_failure_reason(const ProtocolTofEstimate& e)
{
    ExchangeStatus r = ExchangeStatus::InternalError;
    e.failure_reason(r);
    return r;
}

// Drive an SS initiator all the way to the terminal produced by receiving one
// Response, with a caller-chosen local first-path quality.  Returns the
// terminal status (or InternalError if no terminal was produced).
ExchangeStatus run_ss_initiator(const Env& e,
                                const FirstPathQuality& fp,
                                bool* estimate_available = nullptr)
{
    EndpointCore core;
    std::string why;
    if (!core.configure(e.cfg, why))
        return ExchangeStatus::ConfigRejected;

    CoreActionBatch b = core.post(make_begin(1, 1000));
    const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
    if (prep == nullptr)
        return ExchangeStatus::InternalError;
    const TxToken tok = prep->token;
    core.post(make_tx_planned(tok, FrameType::Poll, 2000, e.dom, e.cal.id));
    core.post(outcome_ev(tok, TxOutcome::Completed));

    Frame resp = base_frame(e.cfg, FrameType::Response, 0);
    resp.set(TimestampField::T2B, 2050);
    resp.set(TimestampField::T3B, 2550);
    CoreEvent rx = rx_of(e.cfg, resp, 2600, e.dom, fp);
    CoreActionBatch rb = core.post(rx);

    const CoreAction* tr = find_action(rb, CoreActionKind::TerminalResult);
    if (estimate_available != nullptr)
        *estimate_available = (tr != nullptr) && tr->result.estimate_available;
    return (tr != nullptr) ? action_status(*tr) : ExchangeStatus::Ok;
}

// Build one peer interval from two fields of one frame.
bool peer_interval(FrameType type,
                   TimestampField later_field,
                   uint64_t later_ticks,
                   TimestampField earlier_field,
                   uint64_t earlier_ticks,
                   const WireTimestampBinding& binding,
                   ProtocolInterval& out)
{
    Frame f;
    f.version = kFrameVersion;
    f.function_code = type;
    f.session_id = 1;
    f.seq = 0;
    f.pan_id = 1;
    f.src_addr = 2;
    f.dst_addr = 1;
    f.set(later_field, later_ticks);
    f.set(earlier_field, earlier_ticks);
    PeerTimestampClaim later, earlier;
    if (!make_peer_claim(f, later_field, later) ||
        !make_peer_claim(f, earlier_field, earlier))
        return false;
    return ProtocolInterval::make_peer(later, earlier, binding, out) == PeerClaimError::Ok;
}

// Structural isolation detection (B16).  A member with the given name must not
// exist on an endpoint-visible object.
template <typename T, typename = void>
struct has_distance_member : std::false_type {};
template <typename T>
struct has_distance_member<T, std::void_t<decltype(std::declval<T>().distance_m)>>
    : std::true_type {};

template <typename T, typename = void>
struct has_tof_member : std::false_type {};
template <typename T>
struct has_tof_member<T, std::void_t<decltype(std::declval<T>().tof)>> : std::true_type {};

template <typename T, typename = void>
struct has_truth_member : std::false_type {};
template <typename T>
struct has_truth_member<T, std::void_t<decltype(std::declval<T>().truth)>> : std::true_type {};

} // namespace

// ===========================================================================
// B15 / B02: configuration domain checks and the clock ratio
// ===========================================================================

BOOST_AUTO_TEST_CASE(b15_configure_rejects_out_of_domain_and_unusable_ratio)
{
    const Env e = make_env(Role::Initiator, Protocol::Ss);
    EndpointCore core;
    std::string why;

    CoreConfig bad = e.cfg;
    bad.protocol = static_cast<Protocol>(7);
    BOOST_TEST(!core.configure(bad, why));

    bad = e.cfg;
    bad.role = static_cast<Role>(9);
    BOOST_TEST(!core.configure(bad, why));

    bad = e.cfg;
    bad.sequence_modulus = 5;
    bad.peer_binding.sequence_modulus = 5;
    BOOST_TEST(!core.configure(bad, why));

    bad = e.cfg;
    bad.result_queue_capacity = 0;
    BOOST_TEST(!core.configure(bad, why));

    bad = e.cfg;
    bad.max_in_flight = 2;
    BOOST_TEST(!core.configure(bad, why));

    bad = e.cfg;
    bad.initial_sequence = 4; // == modulus
    BOOST_TEST(!core.configure(bad, why));

    // Missing ratio: a default-constructed ClockRatio is `provided() == false`.
    bad = e.cfg;
    bad.ratio = ClockRatio();
    BOOST_TEST(!core.configure(bad, why));

    // Ratio identity does not match this endpoint's local domain.
    ClockDomain other = make_domain("other_dev", 2.0e9, 1, 40);
    bad = e.cfg;
    ClockRatio r_other;
    ClockRatio::unity_same_clock(other, r_other);
    bad.ratio = r_other;
    BOOST_TEST(!core.configure(bad, why));

    // Lossy local -> wire unit conversion is refused.
    bad = e.cfg;
    bad.frame_profile = make_profile(2.0e9);
    BOOST_TEST(!core.configure(bad, why));

    // The untouched configuration is accepted and becomes immutable authority.
    BOOST_TEST(core.configure(e.cfg, why));
    BOOST_TEST(core.is_configured());
    BOOST_TEST(core.config().session_id == e.cfg.session_id);
}

BOOST_AUTO_TEST_CASE(b02_out_of_window_ratio_is_reported_not_used)
{
    ClockDomain d = make_domain("d", 1.0e9, 1, 40);
    ClockRatio k;
    BOOST_TEST(ClockRatio::unity_same_clock(d, k));
    BOOST_TEST(k.set_validity_window(0, 10));

    WireTimestampBinding b = make_binding(d, 1, 1, 1000000, 4);
    ProtocolInterval ra, db;
    BOOST_TEST(peer_interval(FrameType::Final, TimestampField::T4A, 1600,
                             TimestampField::T1A, 1000, b, ra));
    BOOST_TEST(peer_interval(FrameType::Response, TimestampField::T3B, 2500,
                             TimestampField::T2B, 2000, b, db));

    const ProtocolTofEstimate est = compute_protocol_ss_tof(ra, db, k);
    BOOST_TEST(!est.estimate_available);
    BOOST_TEST(est.math_status == TofStatus::ClockRatioNotValidAtTime);
    BOOST_TEST(est_failure_reason(est) == ExchangeStatus::ClockEstimateInvalid);
}

// ===========================================================================
// B15: enum domain, entry points never throw
// ===========================================================================

BOOST_AUTO_TEST_CASE(b15_out_of_domain_event_has_no_action_and_never_throws)
{
    const Env e = make_env(Role::Initiator, Protocol::Ss);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    CoreEvent ev = make_begin(1, 1000);
    ev.kind = static_cast<CoreEventKind>(200);

    // A configured core reports and ignores.
    CoreActionBatch b = core.post(ev);
    BOOST_TEST(b.count == 0u);
    BOOST_TEST(core.counters().events_rejected_out_of_domain == 1u);
    BOOST_TEST(core.counters().accepted_exchanges == 0u);

    // An unconfigured core does nothing at all (and does not throw).
    EndpointCore fresh;
    CoreActionBatch b2 = fresh.post(ev);
    BOOST_TEST(b2.count == 0u);
}

// ===========================================================================
// B04: PHY verdicts, frame matching, and a legal frame still advancing
// ===========================================================================

BOOST_AUTO_TEST_CASE(b04_bad_fcs_and_decode_do_not_open_an_exchange)
{
    const Env e = make_env(Role::Responder, Protocol::Ss);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    Frame poll = base_frame(e.cfg, FrameType::Poll, 0);

    CoreEvent fcs = rx_of(e.cfg, poll, 2000, e.dom);
    fcs.fcs_passed = false;
    CoreActionBatch b = core.post(fcs);
    BOOST_TEST(b.count == 0u);
    BOOST_TEST(core.counters().frames_rejected_fcs == 1u);
    BOOST_TEST(core.in_flight() == 0u);
    BOOST_TEST(core.counters().accepted_exchanges == 0u);

    CoreEvent dec = rx_of(e.cfg, poll, 2000, e.dom);
    dec.decode_ok = false;
    b = core.post(dec);
    BOOST_TEST(b.count == 0u);
    BOOST_TEST(core.counters().frames_rejected_decode == 1u);
    BOOST_TEST(core.in_flight() == 0u);
}

BOOST_AUTO_TEST_CASE(b04_wrong_fields_do_not_advance_and_a_legal_frame_does)
{
    const Env e = make_env(Role::Initiator, Protocol::Ss, 64);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));
    BOOST_TEST(core.post(make_begin(1, 1000)).count > 0u);
    BOOST_TEST(core.state() == EndpointState::PollSent);

    auto make_resp = [&]() {
        Frame f = base_frame(e.cfg, FrameType::Response, 0);
        f.set(TimestampField::T2B, 2050);
        f.set(TimestampField::T3B, 2550);
        return f;
    };

    {
        Frame f = base_frame(e.cfg, FrameType::Final, 0);
        f.set(TimestampField::T1A, 1);
        f.set(TimestampField::T4A, 2);
        f.set(TimestampField::T5A, 3);
        core.post(rx_of(e.cfg, f, 2600, e.dom));
        BOOST_TEST(core.counters().frames_rejected_wrong_type == 1u);
        BOOST_TEST(core.state() == EndpointState::PollSent);
    }
    {
        Frame f = make_resp();
        f.pan_id = 0x9999;
        core.post(rx_of(e.cfg, f, 2600, e.dom));
        BOOST_TEST(core.counters().frames_rejected_wrong_peer == 1u);
    }
    {
        Frame f = make_resp();
        f.dst_addr = 0x7777;
        core.post(rx_of(e.cfg, f, 2600, e.dom));
        BOOST_TEST(core.counters().frames_rejected_wrong_peer == 2u);
    }
    {
        Frame f = make_resp();
        f.src_addr = 0x7777;
        core.post(rx_of(e.cfg, f, 2600, e.dom));
        BOOST_TEST(core.counters().frames_rejected_wrong_peer == 3u);
    }
    {
        Frame f = make_resp();
        f.session_id = 9;
        core.post(rx_of(e.cfg, f, 2600, e.dom));
        BOOST_TEST(core.counters().frames_rejected_session == 1u);
    }
    {
        // A wrong sequence is its OWN diagnostic (counter frames_rejected_seq).
        Frame f = make_resp();
        f.seq = 1;
        core.post(rx_of(e.cfg, f, 2600, e.dom));
        BOOST_TEST(core.counters().frames_rejected_seq == 1u);
    }

    BOOST_TEST(core.state() == EndpointState::PollSent);
    BOOST_TEST(core.counters().accepted_exchanges == 1u);
    BOOST_TEST(core.counters().frames_accepted == 0u);

    // A subsequent legal frame does advance, by exactly one.
    Frame legal = make_resp();
    core.post(rx_of(e.cfg, legal, 2600, e.dom));
    BOOST_TEST(core.state() == EndpointState::ResponseReceived);
    BOOST_TEST(core.counters().frames_accepted == 1u);
}

BOOST_AUTO_TEST_CASE(b04_codec_rejects_malformed_and_core_never_advances_on_a_failed_decode)
{
    const Env e = make_env(Role::Responder, Protocol::Ss);
    const Frame poll = base_frame(e.cfg, FrameType::Poll, 0);

    uint8_t buf[kMaxFrameBytes];
    size_t n = 0;
    std::string err;
    BOOST_TEST(encode_into(poll, e.prof, buf, sizeof(buf), n, err));
    BOOST_TEST(n == 14u);

    Frame bad = poll;
    bad.flags = 0x0004; // reserved bit 2
    BOOST_TEST(!encode_into(bad, e.prof, buf, sizeof(buf), n, err));

    bad = poll;
    bad.version = 2;
    BOOST_TEST(!encode_into(bad, e.prof, buf, sizeof(buf), n, err));

    bad = poll;
    bad.flags = kFlagStsPresent;
    BOOST_TEST(!encode_into(bad, e.prof, buf, sizeof(buf), n, err));

    uint8_t good[kMaxFrameBytes];
    size_t gn = 0;
    BOOST_TEST(encode_into(poll, e.prof, good, sizeof(good), gn, err));
    Frame dec;
    BOOST_TEST(!decode(good, gn - 1, e.prof, dec, err)); // truncated
    BOOST_TEST(!decode(good, gn + 2, e.prof, dec, err)); // FCS not stripped

    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));
    CoreEvent ev = rx_of(e.cfg, poll, 2000, e.dom);
    ev.decode_ok = false;
    BOOST_TEST(core.post(ev).count == 0u);
    BOOST_TEST(core.in_flight() == 0u);
}

// ===========================================================================
// B05: duplicates / out-of-order / sequence reuse barrier
// ===========================================================================

BOOST_AUTO_TEST_CASE(b05_duplicate_plan_and_duplicate_poll_do_not_double_tx)
{
    const Env e = make_env(Role::Responder, Protocol::Ss, 64);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));
    const Frame poll = base_frame(e.cfg, FrameType::Poll, 0);

    CoreActionBatch b = core.post(rx_of(e.cfg, poll, 2050, e.dom));
    const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
    BOOST_TEST(prep != nullptr);
    const TxToken tok = prep->token;

    CoreActionBatch sub =
        core.post(make_tx_planned(tok, FrameType::Response, 2550, e.dom, e.cal.id));
    BOOST_TEST(has_action(sub, CoreActionKind::SubmitTx));
    BOOST_TEST(core.counters().tx_submitted == 1u);

    // A second plan for the same token is out of order: no second Submit.
    CoreActionBatch dup =
        core.post(make_tx_planned(tok, FrameType::Response, 2550, e.dom, e.cal.id));
    BOOST_TEST(!has_action(dup, CoreActionKind::SubmitTx));
    BOOST_TEST(core.counters().tx_token_mismatch == 1u);
    BOOST_TEST(core.counters().tx_submitted == 1u);

    // A retransmitted Poll while in flight is a duplicate, not a new request.
    core.post(rx_of(e.cfg, poll, 2060, e.dom));
    BOOST_TEST(core.counters().duplicate_frames == 1u);
    BOOST_TEST(core.counters().tx_submitted == 1u);

    // An SS responder has no Final; it is a duplicate for the current state.
    Frame fin = base_frame(e.cfg, FrameType::Final, 0);
    core.post(rx_of(e.cfg, fin, 2070, e.dom));
    BOOST_TEST(core.counters().duplicate_frames == 2u);
}

BOOST_AUTO_TEST_CASE(b05_sequence_modulus_is_the_reuse_barrier_and_reset_clears_it)
{
    const Env e = make_env(Role::Initiator, Protocol::Ss, 4, 0);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    CoreActionBatch b = core.post(make_begin(1, 1000));
    const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
    BOOST_TEST(prep != nullptr);
    CoreActionBatch sub =
        core.post(make_tx_planned(prep->token, FrameType::Poll, 1500, e.dom, e.cal.id));
    const CoreAction* st = find_action(sub, CoreActionKind::SubmitTx);
    BOOST_TEST(st != nullptr);
    Frame f;
    std::string err;
    BOOST_TEST(decode(st->bytes, st->nbytes, e.prof, f, err));
    BOOST_TEST(f.seq == 0u);
    core.post(make_cancel());

    for (uint64_t i = 2; i <= 4; ++i) {
        core.post(make_begin(i, 1000));
        core.post(make_cancel());
    }
    BOOST_TEST(core.counters().accepted_exchanges == 4u);
    BOOST_TEST(core.counters().terminal_results == 4u);

    // The fifth attempt collides with a possibly-live identity: refused.
    CoreActionBatch fifth = core.post(make_begin(5, 1000));
    BOOST_TEST(fifth.count == 0u);
    BOOST_TEST(core.counters().accepted_exchanges == 4u);
    BOOST_TEST(core.counters().stale_events == 1u);

    // A new session generation clears the running sequence.
    core.post(make_reset(2));
    CoreActionBatch nb = core.post(make_begin(6, 1000));
    BOOST_TEST(has_action(nb, CoreActionKind::PrepareTx));
    BOOST_TEST(core.counters().accepted_exchanges == 5u);
}

// ===========================================================================
// B06: TxPlanned validation and "frame fields come from the same plan"
// ===========================================================================

BOOST_AUTO_TEST_CASE(b06_frame_fields_come_from_the_same_plan)
{
    const Env e = make_env(Role::Responder, Protocol::Ss, 256);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    const Frame poll = base_frame(e.cfg, FrameType::Poll, 0);
    CoreActionBatch b = core.post(rx_of(e.cfg, poll, 2050, e.dom));
    const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
    BOOST_TEST(prep != nullptr);

    CoreActionBatch sub =
        core.post(make_tx_planned(prep->token, FrameType::Response, 2550, e.dom, e.cal.id));
    const CoreAction* st = find_action(sub, CoreActionKind::SubmitTx);
    BOOST_TEST(st != nullptr);
    Frame f;
    std::string err;
    BOOST_TEST(decode(st->bytes, st->nbytes, e.prof, f, err));
    BOOST_TEST(f.t2B() == 2050u); // the admitted local Poll RX instant
    BOOST_TEST(f.t3B() == 2550u); // the SAME plan's quantised instant
}

BOOST_AUTO_TEST_CASE(b06_bad_plan_token_domain_and_deadline_verdict_reject_without_submit)
{
    // (a) a plan missing one record is refused
    {
        const Env e = make_env(Role::Initiator, Protocol::Ss, 256);
        EndpointCore core;
        std::string why;
        BOOST_TEST(core.configure(e.cfg, why));
        CoreActionBatch b = core.post(make_begin(1, 1000));
        const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
        BOOST_TEST(prep != nullptr);
        CoreActionBatch r = core.post(make_tx_planned(prep->token, FrameType::Poll, 1500,
                                                      e.dom, e.cal.id, TxOutcome::Unknown,
                                                      /*records_plan*/ false));
        BOOST_TEST(has_action(r, CoreActionKind::AbortPending));
        const CoreAction* tr = find_action(r, CoreActionKind::TerminalResult);
        BOOST_TEST(tr != nullptr);
        BOOST_TEST(action_status(*tr) == ExchangeStatus::InvalidTimeDomain);
        BOOST_TEST(core.counters().tx_submitted == 0u);
        BOOST_TEST(core.in_flight() == 0u);
    }
    // (b) a wrong token never rewrites the plan
    {
        const Env e = make_env(Role::Initiator, Protocol::Ss, 256);
        EndpointCore core;
        std::string why;
        BOOST_TEST(core.configure(e.cfg, why));
        core.post(make_begin(1, 1000));
        TxToken bad;
        bad.valid = true;
        bad.value = 999999;
        CoreActionBatch r =
            core.post(make_tx_planned(bad, FrameType::Poll, 1500, e.dom, e.cal.id));
        BOOST_TEST(r.count == 0u);
        BOOST_TEST(core.counters().tx_token_mismatch == 1u);
        BOOST_TEST(core.in_flight() == 1u);
    }
    // (c) an out-of-domain enum in the plan is reported, not reasoned about
    {
        const Env e = make_env(Role::Initiator, Protocol::Ss, 256);
        EndpointCore core;
        std::string why;
        BOOST_TEST(core.configure(e.cfg, why));
        CoreActionBatch b = core.post(make_begin(1, 1000));
        const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
        BOOST_TEST(prep != nullptr);
        CoreEvent ev =
            make_tx_planned(prep->token, FrameType::Poll, 1500, e.dom, e.cal.id);
        ev.tx_evidence.outcome = static_cast<TxOutcome>(9);
        CoreActionBatch r = core.post(ev);
        BOOST_TEST(has_action(r, CoreActionKind::TerminalResult));
        BOOST_TEST(core.counters().events_rejected_out_of_domain == 1u);
        BOOST_TEST(core.counters().tx_submitted == 0u);
    }
    // (d) an infeasible deadline verdict refuses the submit
    {
        const Env e = make_env(Role::Initiator, Protocol::Ss, 256);
        EndpointCore core;
        std::string why;
        BOOST_TEST(core.configure(e.cfg, why));
        CoreActionBatch b = core.post(make_begin(1, 1000));
        const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
        BOOST_TEST(prep != nullptr);
        CoreActionBatch r = core.post(make_tx_planned(prep->token, FrameType::Poll, 1500,
                                                      e.dom, e.cal.id, TxOutcome::Unknown,
                                                      /*records_plan*/ true,
                                                      /*deadline_feasible*/ false));
        BOOST_TEST(has_action(r, CoreActionKind::AbortPending));
        const CoreAction* tr = find_action(r, CoreActionKind::TerminalResult);
        BOOST_TEST(tr != nullptr);
        BOOST_TEST(action_status(*tr) == ExchangeStatus::DeadlineMissed);
        BOOST_TEST(core.counters().tx_submit_rejected_deadline == 1u);
        BOOST_TEST(core.counters().tx_submitted == 0u);
    }
}

// ===========================================================================
// B07: accepted != completion; RX before outcome; unresolved + deadline
// ===========================================================================

BOOST_AUTO_TEST_CASE(b07_accepted_is_not_completion_and_rx_before_outcome_still_completes)
{
    const Env e = make_env(Role::Initiator, Protocol::Ss, 256);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    CoreActionBatch b = core.post(make_begin(1, 1000));
    const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
    BOOST_TEST(prep != nullptr);
    const TxToken tok = prep->token;
    BOOST_TEST(has_action(core.post(make_tx_planned(tok, FrameType::Poll, 2000, e.dom, e.cal.id)),
                          CoreActionKind::SubmitTx));

    // send() returning is recorded, but is NOT completion.
    CoreActionBatch acc = core.post(make_accepted(tok));
    BOOST_TEST(acc.count == 0u);
    BOOST_TEST(core.counters().tx_accepted == 1u);
    BOOST_TEST(core.in_flight() == 1u);
    BOOST_TEST(core.counters().terminal_results == 0u);

    Frame resp = base_frame(e.cfg, FrameType::Response, 0);
    resp.set(TimestampField::T2B, 2050);
    resp.set(TimestampField::T3B, 2550);
    CoreActionBatch rb = core.post(rx_of(e.cfg, resp, 2600, e.dom));
    BOOST_TEST(core.state() == EndpointState::ResponseReceived);
    BOOST_TEST(!has_action(rb, CoreActionKind::TerminalResult));
    BOOST_TEST(core.counters().terminal_results == 0u);

    CoreActionBatch ob = core.post(outcome_ev(tok, TxOutcome::Completed));
    const CoreAction* tr = find_action(ob, CoreActionKind::TerminalResult);
    BOOST_TEST(tr != nullptr);
    if (tr != nullptr) {
        BOOST_TEST(action_status(*tr) == ExchangeStatus::Ok);
        BOOST_TEST(tr->result.estimate_available);
        // RA = 2600-2000 = 600, DB = 2550-2050 = 500, ToF = 50/1 A ticks.
        BOOST_TEST(tr->result.tof.num == 50);
        BOOST_TEST(tr->result.tof.den == 1);
        BOOST_TEST(tr->result.measurement_valid == false);
        BOOST_TEST(tr->result.execution_mode_is_simulation == true);
        BOOST_TEST(!tr->result.yields_range());
    }
}

BOOST_AUTO_TEST_CASE(b07_unresolved_evidence_with_a_deadline_fails_finitely)
{
    const Env e = make_env(Role::Initiator, Protocol::Ss, 256, 0, 8, 100000);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    CoreActionBatch b = core.post(make_begin(1, 1000));
    const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
    BOOST_TEST(prep != nullptr);
    core.post(make_tx_planned(prep->token, FrameType::Poll, 2000, e.dom, e.cal.id));
    core.post(make_accepted(prep->token));
    BOOST_TEST(core.in_flight() == 1u);

    CoreActionBatch d = core.post(make_deadline(101000));
    const CoreAction* tr = find_action(d, CoreActionKind::TerminalResult);
    BOOST_TEST(tr != nullptr);
    BOOST_TEST(action_status(*tr) == ExchangeStatus::ProtocolTimeout);
    BOOST_TEST(core.in_flight() == 0u);
}

// ===========================================================================
// B08: TX failure outcomes and adapter faults
// ===========================================================================

BOOST_AUTO_TEST_CASE(b08_failure_outcomes_and_faults_fail_without_resend)
{
    struct Case {
        TxOutcome outcome;
        AdapterFault fault;
        ExchangeStatus want;
    };
    const Case cases[] = {
        { TxOutcome::Late, AdapterFault::None, ExchangeStatus::TxLate },
        { TxOutcome::Underflow, AdapterFault::None, ExchangeStatus::TxUnderflow },
        { TxOutcome::Cancelled, AdapterFault::None, ExchangeStatus::Cancelled },
        { TxOutcome::Unknown, AdapterFault::SeqError, ExchangeStatus::TxSeqError },
        { TxOutcome::Unknown, AdapterFault::ChainBroken, ExchangeStatus::TxChainBroken },
    };
    for (const Case& c : cases) {
        const Env e = make_env(Role::Initiator, Protocol::Ss, 256);
        EndpointCore core;
        std::string why;
        BOOST_TEST(core.configure(e.cfg, why));
        CoreActionBatch b = core.post(make_begin(1, 1000));
        const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
        BOOST_TEST(prep != nullptr);
        BOOST_TEST(has_action(
            core.post(make_tx_planned(prep->token, FrameType::Poll, 2000, e.dom, e.cal.id)),
            CoreActionKind::SubmitTx));
        BOOST_TEST(core.counters().tx_submitted == 1u);

        CoreActionBatch r = core.post(outcome_ev(prep->token, c.outcome, c.fault));
        const CoreAction* tr = find_action(r, CoreActionKind::TerminalResult);
        BOOST_TEST(tr != nullptr);
        if (tr != nullptr) {
            BOOST_TEST(action_status(*tr) == c.want);
            BOOST_TEST(!tr->result.estimate_available);
            BOOST_TEST(tr->result.completion == ProtocolCompletionStatus::Failed);
            BOOST_TEST(!tr->result.yields_range());
        }
        // No immediate re-send, and the source is never relabelled.
        BOOST_TEST(!has_action(r, CoreActionKind::SubmitTx));
        BOOST_TEST(core.counters().tx_submitted == 1u);
        BOOST_TEST(core.counters().tx_outcome_failed == 1u);
        BOOST_TEST(core.in_flight() == 0u);
    }
}

// ===========================================================================
// B09: 40-bit wrap policy on the peer-claim interval
// ===========================================================================

BOOST_AUTO_TEST_CASE(b09_wire_tick_space_wrap_and_span_policy)
{
    ClockDomain d = make_domain("dev40", 1.0e9, 1, 40);
    const uint64_t period = clock_domain_wrap_period(d);
    const uint64_t half = period / 2u;
    std::string why;

    WireTimestampBinding b = make_binding(d, 1, 1, half, 4);
    BOOST_TEST(wire_timestamp_binding_is_well_formed(b, why));

    // A wrapping interval is resolved by the modular difference.
    {
        ProtocolInterval iv;
        BOOST_TEST(peer_interval(FrameType::Final, TimestampField::T4A, 100,
                                 TimestampField::T1A, period - 50, b, iv));
        BOOST_TEST(iv.wrapped());
        int64_t n = 0, dn = 0;
        BOOST_TEST(iv.exact_ratio(n, dn));
        BOOST_TEST(n == 150);
        BOOST_TEST(dn == 1);
    }
    // Exactly the half period is legal.
    {
        ProtocolInterval iv;
        BOOST_TEST(peer_interval(FrameType::Final, TimestampField::T4A, half,
                                 TimestampField::T1A, 0, b, iv));
        BOOST_TEST(!iv.wrapped());
        int64_t n = 0, dn = 0;
        BOOST_TEST(iv.exact_ratio(n, dn));
        BOOST_TEST(static_cast<uint64_t>(n) == half);
    }
    // One tick beyond the half period is ambiguous and refused.
    {
        ProtocolInterval iv;
        BOOST_TEST(!peer_interval(FrameType::Final, TimestampField::T4A, half + 1,
                                  TimestampField::T1A, 0, b, iv));

        Frame f;
        f.function_code = FrameType::Final;
        f.set(TimestampField::T4A, half + 1);
        f.set(TimestampField::T1A, 0);
        PeerTimestampClaim later, earlier;
        BOOST_TEST(make_peer_claim(f, TimestampField::T4A, later));
        BOOST_TEST(make_peer_claim(f, TimestampField::T1A, earlier));
        BOOST_TEST(ProtocolInterval::make_peer(later, earlier, b, iv) ==
                   PeerClaimError::IntervalNotFormable);
    }
    // An interval longer than the declared maximum is refused.
    {
        WireTimestampBinding narrow = make_binding(d, 1, 1, 1000, 4);
        ProtocolInterval iv;
        BOOST_TEST(!peer_interval(FrameType::Final, TimestampField::T4A, 1001,
                                  TimestampField::T1A, 0, narrow, iv));
    }
    // A raw value outside the counter's range is refused.
    {
        ProtocolInterval iv;
        BOOST_TEST(!peer_interval(FrameType::Final, TimestampField::T4A, period,
                                  TimestampField::T1A, 0, b, iv));
    }
    // A maximum above the unambiguous half period cannot even be declared.
    {
        WireTimestampBinding over = make_binding(d, 1, 1, half + 1, 4);
        BOOST_TEST(!wire_timestamp_binding_is_well_formed(over, why));
    }
}

// ===========================================================================
// B10: local reset
// ===========================================================================

BOOST_AUTO_TEST_CASE(b10_local_reset_fails_inflight_and_old_events_cannot_revive)
{
    const Env e = make_env(Role::Initiator, Protocol::Ss, 256);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    CoreActionBatch b = core.post(make_begin(1, 1000));
    const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
    BOOST_TEST(prep != nullptr);
    const TxToken stale = prep->token;

    CoreActionBatch r = core.post(make_reset(2));
    BOOST_TEST(has_action(r, CoreActionKind::AbortPending));
    const CoreAction* tr = find_action(r, CoreActionKind::TerminalResult);
    BOOST_TEST(tr != nullptr);
    BOOST_TEST(action_status(*tr) == ExchangeStatus::StaleSession);
    BOOST_TEST(core.in_flight() == 0u);
    BOOST_TEST(core.counters().resets == 1u);

    // The old plan cannot revive the exchange.
    CoreActionBatch old = core.post(make_tx_planned(stale, FrameType::Poll, 2000, e.dom, e.cal.id));
    BOOST_TEST(old.count == 0u);
    BOOST_TEST(core.counters().tx_token_mismatch == 1u);

    // A new session can begin again; old times are not mixed in.
    CoreActionBatch nb = core.post(make_begin(2, 5000));
    BOOST_TEST(has_action(nb, CoreActionKind::PrepareTx));
    BOOST_TEST(core.counters().accepted_exchanges == 2u);
}

// ===========================================================================
// B11: the LOCAL strict gate cannot be supplied by a valid peer frame
// ===========================================================================

BOOST_AUTO_TEST_CASE(b11_local_first_path_and_calibration_are_mandatory)
{
    bool estimate_available = true;

    // First path not recorded -> refused.
    {
        Env e = make_env(Role::Initiator, Protocol::Ss, 256);
        const ExchangeStatus st = run_ss_initiator(
            e, FirstPathQuality::not_recorded(), &estimate_available);
        BOOST_TEST(st == ExchangeStatus::FirstPathUnreliable);
        BOOST_TEST(!estimate_available);
    }
    // First path explicitly failed -> refused.
    {
        Env e = make_env(Role::Initiator, Protocol::Ss, 256);
        const ExchangeStatus st = run_ss_initiator(
            e, FirstPathQuality::failed(5.0, 2.0, 0.4), &estimate_available);
        BOOST_TEST(st == ExchangeStatus::FirstPathUnreliable);
        BOOST_TEST(!estimate_available);
    }
    // No calibration application record -> refused.
    {
        Env e = make_env(Role::Initiator, Protocol::Ss, 256);
        e.cfg.local_calibration.applications.clear();
        const ExchangeStatus st =
            run_ss_initiator(e, FirstPathQuality::passed(20.0, 6.0, 0.9), &estimate_available);
        BOOST_TEST(st == ExchangeStatus::CalibrationMissing);
        BOOST_TEST(!estimate_available);
    }
    // Calibration expired for the exchange instant -> refused.
    {
        Env e = make_env(Role::Initiator, Protocol::Ss, 256);
        e.cfg.local_calibration = make_calibration("cal1", 1, 0, 1000);
        const ExchangeStatus st =
            run_ss_initiator(e, FirstPathQuality::passed(20.0, 6.0, 0.9), &estimate_available);
        BOOST_TEST(st == ExchangeStatus::CalibrationExpired);
        BOOST_TEST(!estimate_available);
    }
}

// ===========================================================================
// B12: peer claims / protocol estimates never become a range
// ===========================================================================

BOOST_AUTO_TEST_CASE(b12_peer_claims_and_protocol_estimate_never_become_a_range)
{
    ClockDomain d = make_domain("d", 1.0e9, 1, 40);
    ClockRatio k;
    BOOST_TEST(ClockRatio::unity_same_clock(d, k));
    WireTimestampBinding b = make_binding(d, 1, 1, 1000000, 4);
    std::string why;

    ProtocolInterval ra, db;
    BOOST_TEST(peer_interval(FrameType::Final, TimestampField::T4A, 1600,
                             TimestampField::T1A, 1000, b, ra));
    BOOST_TEST(peer_interval(FrameType::Response, TimestampField::T3B, 2500,
                             TimestampField::T2B, 2000, b, db));

    const ProtocolTofEstimate est = compute_protocol_ss_tof(ra, db, k);
    BOOST_TEST(est.estimate_available);
    BOOST_TEST(est.tof.num == 50);
    BOOST_TEST(est.tof.den == 1);
    BOOST_TEST(est.peer_evidence_is_wire_claim);
    BOOST_TEST(est.measurement_valid == false);
    BOOST_TEST(est.execution_mode_is_simulation == true);
    BOOST_TEST(!est.yields_range());
    BOOST_TEST(!est.is_hardware_measurement());
    BOOST_TEST(!est.is_validated_measurement());

    // Structural: there is no conversion into the strict types.
    static_assert(!std::is_convertible<ProtocolTofEstimate, TofResult>::value,
                  "a protocol estimate must not convert to a strict TofResult");
    static_assert(!std::is_convertible<ProtocolInterval, AdmittedRangingInterval>::value,
                  "a protocol interval must not convert to an admitted interval");

    // Refusals: an unnamed convention, an over-wide span, an unbound claim and
    // claims from different messages.
    {
        Frame f;
        f.function_code = FrameType::Response;
        f.session_id = 1;
        f.set(TimestampField::T2B, 2000);
        f.set(TimestampField::T3B, 2500);
        PeerTimestampClaim c2, c3;
        BOOST_TEST(make_peer_claim(f, TimestampField::T2B, c2));
        BOOST_TEST(make_peer_claim(f, TimestampField::T3B, c3));

        ProtocolInterval iv;
        WireTimestampBinding bb = b;
        bb.unit_convention.clear();
        BOOST_TEST(ProtocolInterval::make_peer(c3, c2, bb, iv) ==
                   PeerClaimError::BindingNotWellFormed);

        bb = b;
        bb.max_interval_ticks = (1ULL << 39) + 1;
        BOOST_TEST(ProtocolInterval::make_peer(c3, c2, bb, iv) ==
                   PeerClaimError::BindingNotWellFormed);

        PeerTimestampClaim unbound = c2;
        unbound.bound = false;
        BOOST_TEST(ProtocolInterval::make_peer(c3, unbound, b, iv) ==
                   PeerClaimError::ClaimNotBound);

        PeerTimestampClaim other = c3;
        other.message_identity ^= 0x1u;
        BOOST_TEST(ProtocolInterval::make_peer(other, c2, b, iv) ==
                   PeerClaimError::NotSameMessage);
    }

    BOOST_TEST(wire_timestamp_binding_is_well_formed(b, why));
}

// ===========================================================================
// B13: bounded result store
// ===========================================================================

BOOST_AUTO_TEST_CASE(b13_bounded_results_refuse_a_new_begin_without_losing_a_terminal)
{
    const Env e = make_env(Role::Initiator, Protocol::Ss, 256, 0, /*result_cap*/ 1);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    core.post(make_begin(1, 1000));
    core.post(make_cancel(ExchangeStatus::Cancelled));
    BOOST_TEST(core.counters().terminal_results == 1u);

    // The store is full: a new Begin is refused.
    CoreActionBatch b2 = core.post(make_begin(2, 1000));
    BOOST_TEST(b2.count == 0u);
    BOOST_TEST(core.counters().requests_rejected_queue_full == 1u);

    // The already-accepted terminal is never lost.
    ProtocolTofEstimate est;
    BOOST_TEST(core.pop_result(est));
    BOOST_TEST(!core.pop_result(est));

    // Control events are not starved by the full store.
    core.post(make_deadline(50000));
    core.post(make_stop());
    core.post(make_cancel());
    BOOST_TEST(core.counters().requests_rejected_queue_full == 1u);

    // With room again, a new Begin is accepted.
    CoreActionBatch b3 = core.post(make_begin(3, 1000));
    BOOST_TEST(has_action(b3, CoreActionKind::PrepareTx));
    BOOST_TEST(core.counters().accepted_exchanges == 2u);
}

// ===========================================================================
// B14: one terminal per attempt, conservation, restart
// ===========================================================================

BOOST_AUTO_TEST_CASE(b14_exactly_one_terminal_per_attempt_and_conservation_holds)
{
    const Env e = make_env(Role::Initiator, Protocol::Ss, 256);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    CoreActionBatch b = core.post(make_begin(1, 1000));
    const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
    BOOST_TEST(prep != nullptr);
    const TxToken tok = prep->token;
    core.post(make_tx_planned(tok, FrameType::Poll, 2000, e.dom, e.cal.id));

    CoreActionBatch st = core.post(make_stop());
    const CoreAction* tr = find_action(st, CoreActionKind::TerminalResult);
    BOOST_TEST(tr != nullptr);
    BOOST_TEST(action_status(*tr) == ExchangeStatus::Cancelled);
    BOOST_TEST(core.counters().terminal_results == 1u);
    BOOST_TEST(core.in_flight() == 0u);

    // Repeated events after the terminal produce no second terminal.
    core.post(make_stop());
    core.post(make_cancel());
    core.post(make_deadline(999999));
    CoreActionBatch ob = core.post(outcome_ev(tok, TxOutcome::Completed));
    BOOST_TEST(ob.count == 0u);
    BOOST_TEST(core.counters().terminal_results == 1u);
    BOOST_TEST(core.counters().tx_token_mismatch == 1u);

    BOOST_TEST(core.counters().accepted_exchanges ==
               core.counters().terminal_results + core.in_flight());

    // Restart is allowed once the attempt is terminal.
    CoreActionBatch nb = core.post(make_begin(2, 10000));
    BOOST_TEST(has_action(nb, CoreActionKind::PrepareTx));
    core.post(make_stop());
    BOOST_TEST(core.counters().terminal_results == 2u);
    BOOST_TEST(core.counters().accepted_exchanges ==
               core.counters().terminal_results + core.in_flight());
}

// ===========================================================================
// B15: negative ToF kept signed; zero denominator; kernel overflow
// ===========================================================================

BOOST_AUTO_TEST_CASE(b15_negative_tof_kept_signed_and_ds_zero_denominator_reported)
{
    ClockDomain d = make_domain("d", 1.0e9, 1, 40);
    ClockRatio k;
    BOOST_TEST(ClockRatio::unity_same_clock(d, k));
    WireTimestampBinding b = make_binding(d, 1, 1, 1000000, 4);

    ProtocolInterval ra, db;
    // RA = 110-100 = 10, DB = 230-200 = 30 -> (10-30)/2 = -10 A ticks.
    BOOST_TEST(peer_interval(FrameType::Final, TimestampField::T4A, 110,
                             TimestampField::T1A, 100, b, ra));
    BOOST_TEST(peer_interval(FrameType::Response, TimestampField::T3B, 230,
                             TimestampField::T2B, 200, b, db));
    const ProtocolTofEstimate est = compute_protocol_ss_tof(ra, db, k);
    BOOST_TEST(est.tof.num == -10);
    BOOST_TEST(est.tof.den == 1);
    BOOST_TEST(est.tof.negative());
    BOOST_TEST(est.completion == ProtocolCompletionStatus::Failed);
    BOOST_TEST(!est.estimate_available);
    BOOST_TEST(est.math_status == TofStatus::NegativeTof);
    BOOST_TEST(est_failure_reason(est) == ExchangeStatus::NegativeTof);

    // DS with four zero-length intervals -> zero denominator, not a divide by 0.
    ProtocolInterval z;
    BOOST_TEST(peer_interval(FrameType::Response, TimestampField::T3B, 500,
                             TimestampField::T2B, 500, b, z));
    const ProtocolTofEstimate est2 = compute_protocol_ds_tof(z, z, z, z, k);
    BOOST_TEST(est2.math_status == TofStatus::ZeroDenominator);
    BOOST_TEST(!est2.estimate_available);

    // The shared kernel reports overflow instead of wrapping or retrying in
    // double (the M1-A/border case a protocol path cannot otherwise reach).
    {
        using namespace detail;
        Rat128 big = rat128_make(static_cast<i128>(1) << 100, 1);
        Rat128 out;
        const KernelStatus st =
            ds_tof_kernel(big, big, big, big, rat128_make(1, 1), out);
        BOOST_TEST(st == KernelStatus::Overflow);
    }
}

// ===========================================================================
// B16: endpoint input isolation (structural) and a causal deleted-frame test
// ===========================================================================

BOOST_AUTO_TEST_CASE(b16_endpoint_has_no_ground_truth_input_and_a_missing_frame_changes_the_outcome)
{
    static_assert(!has_distance_member<CoreEvent>::value,
                  "CoreEvent must not carry a ground-truth distance");
    static_assert(!has_distance_member<CoreConfig>::value,
                  "CoreConfig must not carry a ground-truth distance");
    static_assert(!has_tof_member<CoreEvent>::value, "CoreEvent must not carry a ToF");
    static_assert(!has_truth_member<CoreEvent>::value, "CoreEvent must not carry a truth field");
    static_assert(!has_distance_member<FakeRx>::value, "FakeRx must not carry a distance");
    static_assert(!has_tof_member<FakeRx>::value, "FakeRx must not carry a ToF");

    const Env e = make_env(Role::Initiator, Protocol::Ss, 256);

    // With the Response: a completed protocol estimate.
    bool with_estimate = false;
    run_ss_initiator(e, FirstPathQuality::passed(20.0, 6.0, 0.9), &with_estimate);
    BOOST_TEST(with_estimate);

    // Without the Response (deleted from the causal chain): the exchange can
    // only end in a timeout, never in the same estimate.
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));
    CoreActionBatch b = core.post(make_begin(1, 1000));
    const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
    BOOST_TEST(prep != nullptr);
    core.post(make_tx_planned(prep->token, FrameType::Poll, 2000, e.dom, e.cal.id));
    core.post(outcome_ev(prep->token, TxOutcome::Completed));
    CoreActionBatch d = core.post(make_deadline(101000));
    const CoreAction* tr = find_action(d, CoreActionKind::TerminalResult);
    BOOST_TEST(tr != nullptr);
    if (tr != nullptr) {
        BOOST_TEST(action_status(*tr) == ExchangeStatus::ProtocolTimeout);
        BOOST_TEST(!tr->result.estimate_available);
    }
}

// ===========================================================================
// F (read-only review) regression cases: the three blocking findings.
// ===========================================================================

// F-B1: the FSM's own output envelope must not carry a status that a range
// helper accepts.  Before the fix, `CoreAction::status` was an ExchangeStatus
// and `exchange_status_yields_range(ExchangeStatus::Ok)` was true on success.
BOOST_AUTO_TEST_CASE(f_b1_protocol_terminal_status_is_not_a_range_status)
{
    static_assert(std::is_same<decltype(CoreAction{}.status), ProtocolTerminalStatus>::value,
                  "CoreAction::status must be the strong ProtocolTerminalStatus");
    static_assert(!std::is_convertible<ProtocolTerminalStatus, ExchangeStatus>::value,
                  "a protocol terminal status must not convert to ExchangeStatus");
    static_assert(!std::is_convertible<ProtocolTerminalStatus, bool>::value,
                  "a protocol terminal status must not be truthy");

    const Env e = make_env(Role::Initiator, Protocol::Ss, 256);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    CoreActionBatch b = core.post(make_begin(1, 1000));
    const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
    BOOST_TEST(prep != nullptr);
    if (prep == nullptr)
        return;
    core.post(make_tx_planned(prep->token, FrameType::Poll, 2000, e.dom, e.cal.id));
    core.post(outcome_ev(prep->token, TxOutcome::Completed));
    Frame resp = base_frame(e.cfg, FrameType::Response, 0);
    resp.set(TimestampField::T2B, 2050);
    resp.set(TimestampField::T3B, 2550);
    CoreActionBatch rb = core.post(rx_of(e.cfg, resp, 2600, e.dom));
    const CoreAction* tr = find_action(rb, CoreActionKind::TerminalResult);
    BOOST_TEST(tr != nullptr);
    if (tr != nullptr) {
        BOOST_TEST(tr->status.completed());
        BOOST_TEST(!tr->status.yields_range());
        BOOST_TEST(!tr->status.measurement_valid());
        BOOST_TEST(tr->result.estimate_available);
        // No failure reason is exposed on a successful exchange, so a caller
        // cannot read an Ok status off this type either.
        ExchangeStatus reason = ExchangeStatus::InternalError;
        BOOST_TEST(!tr->status.failure_reason(reason));
    }
}

// F-B2: `reset()` must not silently discard an in-flight terminal or clear the
// counters; it refuses until the in-flight exchange has a terminal result.
BOOST_AUTO_TEST_CASE(f_b2_reset_refuses_in_flight_and_preserves_counters)
{
    const Env e = make_env(Role::Initiator, Protocol::Ss, 4);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    CoreActionBatch b = core.post(make_begin(1, 1000));
    BOOST_TEST(find_action(b, CoreActionKind::PrepareTx) != nullptr);
    const uint64_t accepted = core.counters().accepted_exchanges;
    BOOST_TEST(accepted == 1u);

    CoreConfig fresh = e.cfg;
    fresh.session_generation = 2;
    fresh.peer_binding.session_generation = 2;

    BOOST_TEST(!core.reset(fresh, 2, why));      // refused: in flight
    BOOST_TEST(core.in_flight() == 1u);
    BOOST_TEST(core.counters().accepted_exchanges == accepted);

    CoreActionBatch s = core.post(make_cancel(ExchangeStatus::Cancelled));
    BOOST_TEST(find_action(s, CoreActionKind::TerminalResult) != nullptr);
    BOOST_TEST(core.in_flight() == 0u);

    BOOST_TEST(core.reset(fresh, 2, why));       // now allowed
    BOOST_TEST(core.counters().accepted_exchanges == accepted);
}

// F-B3: after a local Reset the peer binding is for the OLD generation; a peer
// wire claim must then be refused rather than silently used.
BOOST_AUTO_TEST_CASE(f_b3_stale_peer_binding_generation_is_refused)
{
    const Env e = make_env(Role::Initiator, Protocol::Ss, 4);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    core.post(make_reset(2)); // bumps the session generation; binding stays gen 1

    CoreActionBatch b = core.post(make_begin(9, 1000));
    const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
    BOOST_TEST(prep != nullptr);
    if (prep == nullptr)
        return;
    core.post(make_tx_planned(prep->token, FrameType::Poll, 2000, e.dom, e.cal.id));
    core.post(outcome_ev(prep->token, TxOutcome::Completed));

    Frame resp = base_frame(e.cfg, FrameType::Response, 0);
    resp.set(TimestampField::T2B, 2050);
    resp.set(TimestampField::T3B, 2550);
    CoreActionBatch rb = core.post(rx_of(e.cfg, resp, 2600, e.dom));
    const CoreAction* tr = find_action(rb, CoreActionKind::TerminalResult);
    BOOST_TEST(tr != nullptr);
    if (tr != nullptr) {
        BOOST_TEST(action_status(*tr) == ExchangeStatus::InvalidTimeDomain);
        BOOST_TEST(!tr->result.estimate_available);
    }
}

// F-N1: a responder must not open a second exchange from a replayed Poll whose
// wire sequence was already consumed in this session generation.
BOOST_AUTO_TEST_CASE(f_n1_responder_replay_of_a_consumed_sequence_is_refused)
{
    const Env e = make_env(Role::Responder, Protocol::Ss, 4);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    Frame poll = base_frame(e.cfg, FrameType::Poll, 0);
    CoreActionBatch b1 = core.post(rx_of(e.cfg, poll, 1000, e.dom));
    const CoreAction* prep = find_action(b1, CoreActionKind::PrepareTx);
    BOOST_TEST(prep != nullptr);
    if (prep == nullptr)
        return;
    core.post(make_tx_planned(prep->token, FrameType::Response, 1500, e.dom, e.cal.id));
    core.post(outcome_ev(prep->token, TxOutcome::Completed)); // SS responder terminal

    const uint64_t accepted = core.counters().accepted_exchanges;
    const uint64_t stale = core.counters().stale_events;

    CoreActionBatch b2 = core.post(rx_of(e.cfg, poll, 5000, e.dom));
    BOOST_TEST(find_action(b2, CoreActionKind::PrepareTx) == nullptr);
    BOOST_TEST(core.counters().accepted_exchanges == accepted);
    BOOST_TEST(core.counters().stale_events == stale + 1);
}

// F-N2: an OUT-OF-DOMAIN cancel reason (a numeric gap in ExchangeStatus) must
// be replaced, not stored as-is.
BOOST_AUTO_TEST_CASE(f_n2_out_of_domain_cancel_reason_is_not_stored)
{
    const Env e = make_env(Role::Initiator, Protocol::Ss, 4);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));
    core.post(make_begin(1, 1000));
    // 6 is a numeric gap: no ExchangeStatus enumerator has that value.
    CoreActionBatch b = core.post(make_cancel(static_cast<ExchangeStatus>(6)));
    const CoreAction* tr = find_action(b, CoreActionKind::TerminalResult);
    BOOST_TEST(tr != nullptr);
    if (tr != nullptr) {
        ExchangeStatus reason = ExchangeStatus::Ok;
        BOOST_TEST(tr->status.failure_reason(reason));
        BOOST_TEST(reason == ExchangeStatus::Cancelled);
    }
}

// F-N8: `reset()` must not drop an undrained terminal result.
BOOST_AUTO_TEST_CASE(f_n8_reset_retains_undrained_terminal_results)
{
    const Env e = make_env(Role::Initiator, Protocol::Ss, 4);
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));

    CoreActionBatch b = core.post(make_begin(1, 1000));
    const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
    BOOST_TEST(prep != nullptr);
    if (prep == nullptr)
        return;
    core.post(make_tx_planned(prep->token, FrameType::Poll, 2000, e.dom, e.cal.id));
    core.post(outcome_ev(prep->token, TxOutcome::Completed));
    Frame resp = base_frame(e.cfg, FrameType::Response, 0);
    resp.set(TimestampField::T2B, 2050);
    resp.set(TimestampField::T3B, 2550);
    core.post(rx_of(e.cfg, resp, 2600, e.dom)); // terminal produced, not drained

    BOOST_TEST(core.counters().terminal_results == 1u);
    CoreConfig fresh = e.cfg;
    fresh.session_generation = 2;
    fresh.peer_binding.session_generation = 2;
    BOOST_TEST(core.reset(fresh, 2, why));

    ProtocolTofEstimate retained;
    BOOST_TEST(core.pop_result(retained));
    BOOST_TEST(retained.estimate_available);
}

// F-N10: the result type must not expose a range-compatible status either.
BOOST_AUTO_TEST_CASE(f_n10_estimate_failure_reason_is_failed_only)
{
    static_assert(!std::is_convertible<ProtocolTofEstimate, ExchangeStatus>::value,
                  "a protocol estimate must not convert to ExchangeStatus");

    const Env e = make_env(Role::Initiator, Protocol::Ss, 256);
    bool with_estimate = false;
    const ExchangeStatus st =
        run_ss_initiator(e, FirstPathQuality::passed(20.0, 6.0, 0.9), &with_estimate);
    BOOST_TEST(with_estimate);
    BOOST_TEST(st == ExchangeStatus::Ok);

    // A successful estimate exposes NO failure reason.
    EndpointCore core;
    std::string why;
    BOOST_TEST(core.configure(e.cfg, why));
    CoreActionBatch b = core.post(make_begin(1, 1000));
    const CoreAction* prep = find_action(b, CoreActionKind::PrepareTx);
    BOOST_TEST(prep != nullptr);
    if (prep == nullptr)
        return;
    core.post(make_tx_planned(prep->token, FrameType::Poll, 2000, e.dom, e.cal.id));
    core.post(outcome_ev(prep->token, TxOutcome::Completed));
    Frame resp = base_frame(e.cfg, FrameType::Response, 0);
    resp.set(TimestampField::T2B, 2050);
    resp.set(TimestampField::T3B, 2550);
    CoreActionBatch rb = core.post(rx_of(e.cfg, resp, 2600, e.dom));
    const CoreAction* tr = find_action(rb, CoreActionKind::TerminalResult);
    BOOST_TEST(tr != nullptr);
    if (tr != nullptr) {
        ExchangeStatus reason = ExchangeStatus::InternalError;
        BOOST_TEST(!tr->result.failure_reason(reason));
        BOOST_TEST(!tr->result.yields_range());
    }
}
