/* -*- c++ -*- */
/*
 * Copyright 2026
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * QA for UwbRadarPacketSource (message-only complete-packet loader).
 *
 * Canonical files: testdata/uwb_radar/tx_998p4.cf32 and tx_737p28.cf32
 * generated by export_uwb_radar_golden.m.
 */

#include <boost/test/unit_test.hpp>

#include <gnuradio/blocks/message_debug.h>
#include <gnuradio/top_block.h>
#include <gnuradio/uwb/uwb_radar_packet_source.h>
#include <gnuradio/uwb/uwb_radar_pdu_meta.h>
#include <pmt/pmt.h>

#include <chrono>
#include <cmath>
#include <complex>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>

using gr::uwb::UwbRadarPacketSource;
using gr_complex = std::complex<float>;

namespace {

#ifndef UWB_TESTDATA_DIR
#define UWB_TESTDATA_DIR "../../../testdata"
#endif

std::string testdata_path(const std::string& rel)
{
    const std::string from_def = std::string(UWB_TESTDATA_DIR) + "/" + rel;
    {
        std::ifstream f(from_def, std::ios::binary);
        if (f)
            return from_def;
    }
    const char* prefixes[] = {
        "../../../testdata/",
        "../../testdata/",
        "../testdata/",
        "testdata/",
    };
    for (const char* p : prefixes) {
        const std::string path = std::string(p) + rel;
        std::ifstream f(path, std::ios::binary);
        if (f)
            return path;
    }
    return from_def;
}

bool load_cf32(const std::string& path, std::vector<gr_complex>& out)
{
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f)
        return false;
    const auto bytes = static_cast<size_t>(f.tellg());
    if (bytes == 0 || bytes % sizeof(gr_complex) != 0)
        return false;
    f.seekg(0);
    out.resize(bytes / sizeof(gr_complex));
    f.read(reinterpret_cast<char*>(out.data()),
           static_cast<std::streamsize>(bytes));
    return static_cast<bool>(f);
}

double dict_f64(pmt::pmt_t dict, const char* key, double def)
{
    return gr::uwb::radar_meta::to_f64(
        pmt::dict_ref(dict, pmt::mp(key), pmt::from_double(def)), def);
}

int64_t dict_i64(pmt::pmt_t dict, const char* key, int64_t def)
{
    return gr::uwb::radar_meta::to_i64(
        pmt::dict_ref(dict, pmt::mp(key), pmt::from_long(def)), def);
}

std::string dict_str(pmt::pmt_t dict, const char* key)
{
    pmt::pmt_t v = pmt::dict_ref(dict, pmt::mp(key), pmt::PMT_NIL);
    if (pmt::is_symbol(v))
        return pmt::symbol_to_string(v);
    return {};
}

pmt::pmt_t run_emit(UwbRadarPacketSource::sptr blk,
                    pmt::pmt_t emit_msg,
                    gr::blocks::message_debug::sptr* status_out = nullptr)
{
    auto dbg = gr::blocks::message_debug::make();
    auto st = gr::blocks::message_debug::make();
    auto tb = gr::make_top_block("qa_radar_packet_source");
    tb->msg_connect(blk, "tx", dbg, "store");
    tb->msg_connect(blk, "status", st, "store");
    tb->start();
    blk->_post(pmt::mp("emit"), emit_msg);
    for (int i = 0; i < 200 && dbg->num_messages() == 0 &&
                    blk->pdus_dropped() == 0; ++i)
        std::this_thread::sleep_for(std::chrono::milliseconds(1));
    tb->stop();
    tb->wait();
    if (status_out)
        *status_out = st;
    if (dbg->num_messages() == 0)
        return pmt::PMT_NIL;
    return dbg->get_message(0);
}

} // namespace

BOOST_AUTO_TEST_CASE(test_read_tx_998p4_bit_exact)
{
    const std::string path = testdata_path("uwb_radar/tx_998p4.cf32");
    std::vector<gr_complex> file;
    BOOST_REQUIRE_MESSAGE(load_cf32(path, file), "cannot load " + path);
    BOOST_REQUIRE_EQUAL(file.size(), 190912u);

    auto blk = UwbRadarPacketSource::make(path, 998.4e6);
    BOOST_REQUIRE_EQUAL(blk->num_samples(), 190912u);
    BOOST_REQUIRE_EQUAL(blk->samples().size(), file.size());
    BOOST_REQUIRE_EQUAL(std::memcmp(blk->samples().data(), file.data(),
                                    file.size() * sizeof(gr_complex)),
                        0);

    pmt::pmt_t pdu = run_emit(blk, pmt::make_dict());
    BOOST_REQUIRE(pmt::is_pair(pdu));
    pmt::pmt_t meta = pmt::car(pdu);
    pmt::pmt_t data = pmt::cdr(pdu);
    BOOST_REQUIRE(pmt::is_c32vector(data));
    size_t n = 0;
    const gr_complex* p = pmt::c32vector_elements(data, n);
    BOOST_REQUIRE_EQUAL(n, file.size());
    BOOST_REQUIRE_EQUAL(
        std::memcmp(p, file.data(), file.size() * sizeof(gr_complex)), 0);

    BOOST_CHECK_CLOSE(dict_f64(meta, "sample_rate", 0.0), 998.4e6, 1e-4);
    BOOST_CHECK_EQUAL(dict_i64(meta, "tx_packet_samples", -1), 190912);
    BOOST_CHECK_EQUAL(dict_i64(meta, "sample_count", -1), 190912);
    BOOST_CHECK_EQUAL(dict_i64(meta, "sync_repetitions", -1), 64);
    BOOST_CHECK_EQUAL(dict_str(meta, "sfd_mode"), std::string("4z2"));
    BOOST_CHECK_EQUAL(dict_i64(meta, "code_index", -1), 9);
    BOOST_CHECK_EQUAL(dict_str(meta, "sample_format"), std::string("fc32"));
    BOOST_CHECK_EQUAL(dict_str(meta, "source"), std::string("packet_source"));
    BOOST_CHECK_EQUAL(dict_i64(meta, "pulse_id", -1), 0);
    BOOST_CHECK_EQUAL(dict_i64(meta, "sync_samples", -1), 64 * 1016);
    BOOST_CHECK_EQUAL(dict_i64(meta, "sfd_samples", -1), 8 * 1016);
    BOOST_CHECK_EQUAL(blk->pdus_emitted(), 1u);
}

BOOST_AUTO_TEST_CASE(test_read_tx_737p28_bit_exact)
{
    const std::string path = testdata_path("uwb_radar/tx_737p28.cf32");
    std::vector<gr_complex> file;
    BOOST_REQUIRE_MESSAGE(load_cf32(path, file), "cannot load " + path);
    BOOST_REQUIRE_EQUAL(file.size(), 140982u);

    auto blk = UwbRadarPacketSource::make(path, 737.28e6);
    BOOST_REQUIRE_EQUAL(blk->num_samples(), 140982u);
    BOOST_REQUIRE_EQUAL(std::memcmp(blk->samples().data(), file.data(),
                                    file.size() * sizeof(gr_complex)),
                        0);

    pmt::pmt_t pdu = run_emit(blk, pmt::make_dict());
    BOOST_REQUIRE(pmt::is_pair(pdu));
    pmt::pmt_t meta = pmt::car(pdu);
    pmt::pmt_t data = pmt::cdr(pdu);
    size_t n = 0;
    const gr_complex* p = pmt::c32vector_elements(data, n);
    BOOST_REQUIRE_EQUAL(n, 140982u);
    BOOST_REQUIRE_EQUAL(
        std::memcmp(p, file.data(), file.size() * sizeof(gr_complex)), 0);
    BOOST_CHECK_CLOSE(dict_f64(meta, "sample_rate", 0.0), 737.28e6, 1e-4);
    BOOST_CHECK_EQUAL(dict_i64(meta, "tx_packet_samples", -1), 140982);
    BOOST_CHECK_EQUAL(blk->pdus_emitted(), 1u);
}

BOOST_AUTO_TEST_CASE(test_pulse_id_increment_and_override)
{
    const std::string path = testdata_path("uwb_radar/tx_998p4.cf32");
    auto blk = UwbRadarPacketSource::make(path, 998.4e6);

    pmt::pmt_t a = run_emit(blk, pmt::PMT_NIL);
    BOOST_CHECK_EQUAL(dict_i64(pmt::car(a), "pulse_id", -1), 0);

    pmt::pmt_t b = run_emit(blk, pmt::make_dict());
    BOOST_CHECK_EQUAL(dict_i64(pmt::car(b), "pulse_id", -1), 1);

    pmt::pmt_t dict = pmt::make_dict();
    dict = pmt::dict_add(dict, pmt::mp("pulse_id"), pmt::from_uint64(7));
    pmt::pmt_t c = run_emit(blk, dict);
    BOOST_CHECK_EQUAL(dict_i64(pmt::car(c), "pulse_id", -1), 7);
}

BOOST_AUTO_TEST_CASE(test_auto_emit_once)
{
    const std::string path = testdata_path("uwb_radar/tx_998p4.cf32");
    auto dbg = gr::blocks::message_debug::make();
    auto blk = UwbRadarPacketSource::make(
        path, 998.4e6, "fc32", 64, "4z2", 9, 0.005, true);
    auto tb = gr::make_top_block("qa_packet_source_auto");
    tb->msg_connect(blk, "tx", dbg, "store");
    tb->start();
    for (int i = 0; i < 200 && dbg->num_messages() == 0; ++i)
        std::this_thread::sleep_for(std::chrono::milliseconds(1));
    tb->stop();
    tb->wait();
    BOOST_REQUIRE_EQUAL(dbg->num_messages(), 1u);
    BOOST_CHECK_EQUAL(blk->pdus_emitted(), 1u);
}

BOOST_AUTO_TEST_CASE(test_invalid_empty_file_throws)
{
    const std::string empty_path = "/tmp/uwb_qa_empty_packet.cf32";
    {
        std::ofstream f(empty_path, std::ios::binary | std::ios::trunc);
        BOOST_REQUIRE(f);
    }
    bool ok = true;
    try {
        (void)UwbRadarPacketSource::make(empty_path, 998.4e6);
    } catch (const std::exception&) {
        ok = false;
    }
    BOOST_REQUIRE(!ok);
}

BOOST_AUTO_TEST_CASE(test_invalid_missing_file_throws)
{
    bool ok = true;
    try {
        (void)UwbRadarPacketSource::make(
            "/no/such/uwb_radar_packet.cf32", 998.4e6);
    } catch (const std::exception&) {
        ok = false;
    }
    BOOST_REQUIRE(!ok);
}

BOOST_AUTO_TEST_CASE(test_invalid_bad_rate_throws)
{
    const std::string path = testdata_path("uwb_radar/tx_998p4.cf32");
    bool ok = true;
    try {
        (void)UwbRadarPacketSource::make(path, 1.0e6);
    } catch (const std::exception&) {
        ok = false;
    }
    BOOST_REQUIRE(!ok);
}

BOOST_AUTO_TEST_CASE(test_invalid_sfd_mode_and_code_index)
{
    const std::string path = testdata_path("uwb_radar/tx_998p4.cf32");
    bool ok = true;
    try {
        (void)UwbRadarPacketSource::make(path, 998.4e6, "fc32", 64, "nope", 9);
    } catch (const std::exception&) {
        ok = false;
    }
    BOOST_REQUIRE(!ok);

    ok = true;
    try {
        (void)UwbRadarPacketSource::make(path, 998.4e6, "fc32", 64, "4z2", 8);
    } catch (const std::exception&) {
        ok = false;
    }
    BOOST_REQUIRE(!ok);
}

bool throws_make(const std::string& path,
                 double rate,
                 const std::string& fmt,
                 size_t sync = 64,
                 const std::string& sfd = "4z2",
                 size_t code = 9,
                 const std::string& descriptor = "")
{
    try {
        (void)UwbRadarPacketSource::make(
            path, rate, fmt, sync, sfd, code, 0.005, false, descriptor);
        return false;
    } catch (const std::exception&) {
        return true;
    }
}

bool load_sc16(const std::string& path, std::vector<int16_t>& out)
{
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f)
        return false;
    const auto bytes = static_cast<size_t>(f.tellg());
    if (bytes == 0 || bytes % sizeof(int16_t) != 0)
        return false;
    f.seekg(0);
    out.resize(bytes / sizeof(int16_t));
    f.read(reinterpret_cast<char*>(out.data()),
           static_cast<std::streamsize>(bytes));
    return static_cast<bool>(f);
}

void write_descriptor(const std::string& path,
                      const std::string& sample_format,
                      const std::string& dtype,
                      const std::string& byte_order,
                      const std::string& layout,
                      int64_t length)
{
    std::ofstream f(path, std::ios::binary | std::ios::trunc);
    BOOST_REQUIRE_MESSAGE(f, "cannot create " + path);
    f << "{\"sample_format\":\"" << sample_format
      << "\",\"dtype\":\"" << dtype
      << "\",\"byte_order\":\"" << byte_order
      << "\",\"layout\":\"" << layout
      << "\",\"bytes_per_complex\":"
      << (sample_format == "fc32" ? 8 : 4)
      << ",\"rate_work_hz\":998400000"
      << ",\"rate_native_hz\":737280000"
      << ",\"sync_repetitions\":64"
      << ",\"sfd_mode\":\"4z2\""
      << ",\"code_index\":9"
      << ",\"tx_length_998p4\":" << length
      << ",\"tx_length_737p28\":" << length << "}";
    BOOST_REQUIRE_MESSAGE(f.good(), "failed writing " + path);
}

BOOST_AUTO_TEST_CASE(test_native_requires_complete_descriptor)
{
    const std::string short_path = "/tmp/uwb_qa_short_native.cf32";
    {
        std::vector<gr_complex> iq(8, gr_complex(0.1f, 0.0f));
        std::ofstream f(short_path, std::ios::binary);
        BOOST_REQUIRE(f);
        f.write(reinterpret_cast<const char*>(iq.data()),
                static_cast<std::streamsize>(iq.size() * sizeof(gr_complex)));
    }
    BOOST_REQUIRE(throws_make(short_path, 737.28e6, "fc32"));
}

BOOST_AUTO_TEST_CASE(test_native_profile_mismatch_throws)
{
    const std::string path = testdata_path("uwb_radar/tx_737p28.cf32");
    BOOST_REQUIRE(throws_make(path, 737.28e6, "fc32", 32));
    BOOST_REQUIRE(throws_make(path, 737.28e6, "fc32", 128));
}

BOOST_AUTO_TEST_CASE(test_native_sync32_complete_packet)
{
    const std::string path =
        testdata_path("uwb_radar/packets/sync32/tx_737p28.cf32");
    std::vector<gr_complex> file;
    BOOST_REQUIRE_MESSAGE(load_cf32(path, file), "cannot load " + path);
    auto blk = UwbRadarPacketSource::make(
        path, 737.28e6, "fc32", 32, "4z2", 9);
    BOOST_REQUIRE_EQUAL(blk->num_samples(), file.size());
    pmt::pmt_t pdu = run_emit(blk, pmt::make_dict());
    BOOST_REQUIRE(pmt::is_pair(pdu));
    BOOST_CHECK_EQUAL(dict_i64(pmt::car(pdu), "sync_repetitions", -1), 32);
    BOOST_CHECK_EQUAL(dict_i64(pmt::car(pdu), "tx_packet_samples", -1),
                      static_cast<int64_t>(file.size()));
}

BOOST_AUTO_TEST_CASE(test_sc16_998p4_golden)
{
    const std::string path = testdata_path("uwb_radar/tx_998p4.sc16");
    const std::string head = testdata_path("uwb_radar/tx_998p4_sc16_head16.i16");
    std::vector<int16_t> file, head16;
    BOOST_REQUIRE_MESSAGE(load_sc16(path, file), "cannot load " + path);
    BOOST_REQUIRE_MESSAGE(load_sc16(head, head16), "cannot load " + head);
    BOOST_REQUIRE_EQUAL(file.size(), 190912u * 2u);
    BOOST_REQUIRE_EQUAL(head16.size(), 32u);
    BOOST_REQUIRE_EQUAL(std::memcmp(file.data(), head16.data(),
                                    head16.size() * sizeof(int16_t)),
                        0);

    auto blk = UwbRadarPacketSource::make(path, 998.4e6, "sc16");
    BOOST_REQUIRE_EQUAL(blk->num_samples(), 190912u);
    BOOST_REQUIRE_EQUAL(blk->sc16_samples().size(), file.size());
    BOOST_REQUIRE_EQUAL(std::memcmp(blk->sc16_samples().data(), file.data(),
                                    file.size() * sizeof(int16_t)),
                        0);

    pmt::pmt_t pdu = run_emit(blk, pmt::make_dict());
    BOOST_REQUIRE(pmt::is_pair(pdu));
    pmt::pmt_t meta = pmt::car(pdu);
    pmt::pmt_t data = pmt::cdr(pdu);
    BOOST_REQUIRE(pmt::is_s16vector(data));
    BOOST_REQUIRE(!pmt::is_c32vector(data));
    size_t n = 0;
    const int16_t* p = pmt::s16vector_elements(data, n);
    BOOST_REQUIRE_EQUAL(n, file.size());
    BOOST_REQUIRE_EQUAL(std::memcmp(p, file.data(),
                                    file.size() * sizeof(int16_t)),
                        0);
    BOOST_CHECK_EQUAL(dict_str(meta, "sample_format"), std::string("sc16"));
    BOOST_CHECK_CLOSE(dict_f64(meta, "sample_rate", 0.0), 998.4e6, 1e-4);
    BOOST_CHECK_EQUAL(dict_i64(meta, "tx_packet_samples", -1), 190912);
    BOOST_CHECK_EQUAL(dict_i64(meta, "sample_count", -1), 190912);
    BOOST_CHECK_EQUAL(dict_i64(meta, "sync_repetitions", -1), 64);
    BOOST_CHECK_EQUAL(dict_str(meta, "sfd_mode"), std::string("4z2"));
    BOOST_CHECK_EQUAL(dict_i64(meta, "code_index", -1), 9);
}

BOOST_AUTO_TEST_CASE(test_sc16_native_737p28_golden)
{
    const std::string path = testdata_path("uwb_radar/tx_737p28.sc16");
    std::vector<int16_t> file;
    BOOST_REQUIRE_MESSAGE(load_sc16(path, file), "cannot load " + path);
    BOOST_REQUIRE_EQUAL(file.size(), 140982u * 2u);
    auto blk = UwbRadarPacketSource::make(path, 737.28e6, "sc16");
    BOOST_REQUIRE_EQUAL(blk->num_samples(), 140982u);
    pmt::pmt_t pdu = run_emit(blk, pmt::make_dict());
    BOOST_REQUIRE(pmt::is_pair(pdu));
    BOOST_REQUIRE(pmt::is_s16vector(pmt::cdr(pdu)));
    BOOST_CHECK_EQUAL(dict_str(pmt::car(pdu), "sample_format"),
                      std::string("sc16"));
    BOOST_CHECK_EQUAL(dict_i64(pmt::car(pdu), "tx_packet_samples", -1),
                      140982);
}

BOOST_AUTO_TEST_CASE(test_invalid_dtype_and_odd_bytes)
{
    const std::string path = testdata_path("uwb_radar/tx_998p4.cf32");
    BOOST_REQUIRE(throws_make(path, 998.4e6, "f32"));

    const std::string odd = "/tmp/uwb_qa_odd_sc16.sc16";
    {
        std::ofstream f(odd, std::ios::binary);
        BOOST_REQUIRE(f);
        const char bytes[3] = { 1, 2, 3 };
        f.write(bytes, 3);
    }
    BOOST_REQUIRE(throws_make(odd, 998.4e6, "sc16"));
}

BOOST_AUTO_TEST_CASE(test_descriptor_binds_sample_format_and_byte_layout)
{
    // Native rate avoids the work-domain SYNC+SFD minimum-length check: both
    // files deliberately decode to four complex samples, so a rejection here
    // can only come from the descriptor's byte-format contract.
    const std::string fc32_path = "/tmp/uwb_qa_descriptor_fc32.bin";
    const std::string sc16_path = "/tmp/uwb_qa_descriptor_sc16.bin";
    const std::string fc32_desc = "/tmp/uwb_qa_descriptor_fc32.json";
    const std::string sc16_desc = "/tmp/uwb_qa_descriptor_sc16.json";
    const std::string bad_order_desc = "/tmp/uwb_qa_descriptor_bad_order.json";

    const std::vector<gr_complex> fc32(4, gr_complex(0.25f, -0.5f));
    {
        std::ofstream f(fc32_path, std::ios::binary | std::ios::trunc);
        BOOST_REQUIRE(f);
        f.write(reinterpret_cast<const char*>(fc32.data()),
                static_cast<std::streamsize>(fc32.size() * sizeof(gr_complex)));
        BOOST_REQUIRE(f.good());
    }
    const std::vector<int16_t> sc16 = { 100, -200, 300, -400,
                                        500, -600, 700, -800 };
    {
        std::ofstream f(sc16_path, std::ios::binary | std::ios::trunc);
        BOOST_REQUIRE(f);
        f.write(reinterpret_cast<const char*>(sc16.data()),
                static_cast<std::streamsize>(sc16.size() * sizeof(int16_t)));
        BOOST_REQUIRE(f.good());
    }

    write_descriptor(fc32_desc, "fc32", "complex64", "little-endian",
                     "interleaved_iq", 4);
    write_descriptor(sc16_desc, "sc16", "int16", "little-endian",
                     "interleaved_iq", 4);
    write_descriptor(bad_order_desc, "fc32", "complex64", "big-endian",
                     "interleaved_iq", 4);

    // The matching descriptor permits the tiny native fixture.
    auto ok = UwbRadarPacketSource::make(
        fc32_path, 737.28e6, "fc32", 64, "4z2", 9, 0.005, false, fc32_desc);
    BOOST_CHECK_EQUAL(ok->num_samples(), 4u);

    // Both files present exactly four samples in their selected format. A
    // length-only descriptor check would accept these two calls.
    BOOST_REQUIRE(throws_make(fc32_path, 737.28e6, "fc32", 64, "4z2", 9,
                              sc16_desc));
    BOOST_REQUIRE(throws_make(sc16_path, 737.28e6, "sc16", 64, "4z2", 9,
                              fc32_desc));
    BOOST_REQUIRE(throws_make(fc32_path, 737.28e6, "fc32", 64, "4z2", 9,
                              bad_order_desc));
}

BOOST_AUTO_TEST_CASE(test_unsupported_sync_reps_throws)
{
    const std::string path = testdata_path("uwb_radar/tx_998p4.cf32");
    BOOST_REQUIRE(throws_make(path, 998.4e6, "fc32", 16));
    BOOST_REQUIRE(throws_make(path, 998.4e6, "fc32", 0));
    BOOST_REQUIRE(throws_make(path, 998.4e6, "fc32", 48));
    BOOST_REQUIRE(throws_make(path, 998.4e6, "fc32", 4096));
    BOOST_CHECK(gr::uwb::radar_meta::sync_reps_supported(32));
    BOOST_CHECK(gr::uwb::radar_meta::sync_reps_supported(256));
    BOOST_CHECK(gr::uwb::radar_meta::sync_reps_supported(512));
    BOOST_CHECK(gr::uwb::radar_meta::sync_reps_supported(1024));
    BOOST_CHECK(gr::uwb::radar_meta::sync_reps_supported(2048));
    BOOST_CHECK(!gr::uwb::radar_meta::sync_reps_supported(4096));
}

BOOST_AUTO_TEST_CASE(test_sync256_min_length_work_packet)
{
    const size_t n_sync = 256;
    const size_t n = n_sync * 1016 + 8 * 1016;
    const std::string path = "/tmp/uwb_qa_sync256_min.cf32";
    {
        std::vector<gr_complex> z(n, gr_complex(0.01f, 0.0f));
        std::ofstream f(path, std::ios::binary);
        BOOST_REQUIRE(f);
        f.write(reinterpret_cast<const char*>(z.data()),
                static_cast<std::streamsize>(n * sizeof(gr_complex)));
    }
    auto blk = UwbRadarPacketSource::make(path, 998.4e6, "fc32", n_sync);
    BOOST_CHECK_EQUAL(blk->num_samples(), n);
    BOOST_CHECK_EQUAL(blk->sync_repetitions(), n_sync);
    pmt::pmt_t pdu = run_emit(blk, pmt::make_dict());
    BOOST_REQUIRE(pmt::is_pair(pdu));
    BOOST_CHECK_EQUAL(dict_i64(pmt::car(pdu), "sync_repetitions", -1),
                      static_cast<int64_t>(n_sync));
    BOOST_CHECK_EQUAL(dict_i64(pmt::car(pdu), "sync_samples", -1),
                      static_cast<int64_t>(n_sync * 1016));
}
