% Design authority / cross-check for the 65/48 anti-image resampler filter
% (737.28 MS/s -> 998.4 MS/s).  The canonical taps live in
% resampler_65_48/taps_{quality,realtime}.txt (generated by the Python
% design script).  This MATLAB script designs the same filter with MATLAB's
% own kaiserord/fir1, verifies against the canonical file, and prints the
% design metrics required by 开发方案 §5.2.
%
% If the two designs agree within TOL the MATLAB design is a faithful
% regeneration; otherwise the checked-in canonical taps remain authoritative
% and this script reports the difference.
%
% Run from the repo root:
%   matlab -batch "testdata/design_resampler_737p28_to_998p4"
% or open in MATLAB and run the function.

function design_resampler_737p28_to_998p4()
    R_in = 737.28e6;            % input  rate
    R_out = 998.4e6;            % output rate
    L = 65; M = 48;             % interp / decim
    R_v = L * R_in;             % virtual rate
    ripplespec = 0.1;           % passband ripple [dB]
    attenspec  = 70.0;          % stopband attenuation [dB]

    profiles = struct('name', {'quality', 'realtime'}, 'B_mhz', {330, 290});

    for k = 1:numel(profiles)
        p = profiles(k);
        B = p.B_mhz * 1e6;
        sb = R_in - B;                      % first image start
        fcuts = [B, sb];
        mags  = [1, 0];
        dev   = [10^(ripplespec/20)-1, 10^(-attenspec/20)];
        [n, Wn, beta, ftype] = kaiserord(fcuts, mags, dev, R_v);
        if mod(n, 2) == 0, n = n + 1; end
        h = fir1(n, Wn, ftype, kaiser(n+1, beta), 'noscale');
        h = h * L;                          % DC gain == L

        % ---- verify ----
        [Hb, f] = freqz(h, 1, 16384, R_v);
        m = 20*log10(abs(Hb));
        pb_ripple = max(m(f <= B)) - min(m(f <= B));
        sb_worst  = max(m(f >= sb));
        dc = sum(h);
        gd_v = (n)/2;                       % (N-1)/2 virtual samples
        fprintf('[%s] B=%d MHz taps=%d beta=%.3f arms=%d dc=%.4f\n', ...
                p.name, p.B_mhz, numel(h), beta, ceil(numel(h)/L), dc);
        fprintf('   pb_ripple=%.4f dB  sb_worst=%.2f dB  gd_in=%.2f gd_out=%.2f\n', ...
                pb_ripple, sb_worst, gd_v/L, gd_v/M);

        % ---- cross-check canonical ----
        canon = sprintf('testdata/resampler_65_48/taps_%s.txt', p.name);
        if exist(canon, 'file')
            c = readmatrix(canon, 'FileType', 'text');
            if numel(c) ~= numel(h)
                fprintf('   WARNING: canonical %s has %d taps, MATLAB design has %d\n', ...
                        canon, numel(c), numel(h));
            else
                md = max(abs(c(:) - h(:)));
                fprintf('   max|canonical - MATLAB| = %.3e  %s\n', md, ...
                        tern(md < 1e-3, 'MATCH', 'MISMATCH (canonical stays authoritative)'));
            end
        end

        % export MATLAB's own design (informational, non-destructive)
        out = sprintf('testdata/resampler_65_48/taps_%s_matlab.txt', p.name);
        writematrix(h, out, 'FileType', 'text');
        fprintf('   wrote %s\n', out);
    end
end

function s = tern(c, a, b)
    if c, s = a; else, s = b; end
end
