% Export 65/48 resampler golden vectors with MATLAB's own upfirdn.
%
% Each golden is a pair:
%   <name>_in.cf32  : 737.28 MS/s complex input  (block consumes this)
%   <name>_out.cf32 : 998.4 MS/s complex output  (MATLAB upfirdn, canonical)
%
% scipy.signal.upfirdn(h, x, up, down) implements the same polyphase
% operation as MATLAB's upfirdn(x, h, up, down).  The checked-in canonical
% goldens in resampler_65_48/golden/ are generated by the Python exporter;
% this script reproduces them on a MATLAB machine for cross-tool
% verification and optional regeneration.
%
% Run from repo root:
%   matlab -batch "testdata/export_resampler_65_48_golden"
%
% After running, diff the regenerated _in/_out pairs against the checked-in
% ones; they must agree to float32 precision.

function export_resampler_65_48_golden()
    L = 65; M = 48;
    R_in = 737.28e6;
    here = fileparts(mfilename('fullpath'));
    res  = fullfile(here, 'resampler_65_48');
    gold = fullfile(res, 'golden');
    if ~exist(gold, 'dir'), mkdir(gold); end

    taps = readtaps(fullfile(res, 'taps_quality.txt'));
    n_in = 4096;

    % ---- synthetic ----
    t = (0:n_in-1)' / R_in;
    x_impulse = complex(zeros(n_in,1)); x_impulse(1) = 1;
    x_dc      = complex(ones(n_in,1));
    x_tone_low = exp(2j*pi*10e6*t);
    x_tone_pb  = exp(2j*pi*300e6*t);
    x_tone_sb  = exp(2j*pi*420e6*t);
    rng(20260811);
    z = (randn(n_in,1) + 1j*randn(n_in,1))/sqrt(2);
    x_random = z;

    % ---- real UWB window (decimate 998.4 -> 737.28 then resample up) ----
    cfile = fullfile(here, 'uwb_code9_preamble64_payload128_standard_sfd.cfile');
    fid = fopen(cfile, 'rb'); x998 = fread(fid, Inf, 'single=>single');
    fclose(fid);
    x998 = complex(x998(1:2:end), x998(2:2:end));
    win = x998(4992001 : 4992000 + 8192);           % preamble window
    dec_taps = readtaps(fullfile(res, 'taps_realtime.txt'));
    x737 = upfirdn(win, dec_taps, M, L);            % 48/65 decimate

    names = {'impulse','dc','tone_low','tone_pb','tone_sb','random','uwb'};
    xs    = {x_impulse, x_dc, x_tone_low, x_tone_pb, x_tone_sb, x_random, x737};
    for k = 1:numel(names)
        x = xs{k};
        y = upfirdn(x, taps, L, M);                 % canonical golden
        write_cf32(fullfile(gold, [names{k} '_in.cf32']), x);
        write_cf32(fullfile(gold, [names{k} '_out.cf32']), y);
        fprintf('[%s] in=%d out=%d\n', names{k}, numel(x), numel(y));
    end
    fprintf('golden_meta: n_input=%d interpolation=%d decimation=%d\n', ...
            n_in, L, M);
end

function t = readtaps(p)
    t = readmatrix(p, 'FileType', 'text');
end

function write_cf32(p, z)
    inter = [real(z(:)), imag(z(:))].';
    fid = fopen(p, 'wb'); fwrite(fid, inter(:), 'single'); fclose(fid);
end
