%% Generate a deterministic HRP UWB COMM-interference sample for GNU Radio.
%
% A DIFFERENT-preamble signal from the radar (Code Index 10 vs the radar's
% 9), with a short preamble and a small payload.  Used by
% benchmark_detector's scheduled-mixed mode to superpose real comm IQ onto
% the radar stream (true complex-sum interference), unlike the old
% sparse-spike placeholder.
%
% The preamble / SFD / PHR / PSDU are generated by MATLAB's 802.15.4a HRP
% waveform generator (same library as generate_uwb_gnuradio_sample.m, which
% produced the code-9 radar testdata).  FCS validity is irrelevant for
% interference testing, so the PSDU is a fixed 8-byte deterministic pattern.
%
% Output:  uwb_code10_preamble16_payload8.cfile  (CF32 interleaved I/Q)

clear; close all; clc;

fs = 998.4e6;
mean_prf_mhz = 62.4;
data_rate_mbps = 6.81;
code_index = 10;          % DIFFERENT preamble code from the radar (9)
preamble_symbols = 16;    % short comm preamble (radar uses 64)
samples_per_pulse = 2;
psdu_bytes = 8;           % small payload (<=127: no extension hack needed)
peak_amplitude = 1.0;

%% Deterministic PSDU bits (LSB-first per byte, as the generator expects).
payload = uint8(1:psdu_bytes);
bits = zeros(psdu_bytes * 8, 1);
for i = 1:numel(bits)
    bits(i) = bitand(bitshift(uint16(payload(floor((i - 1) / 8) + 1)), ...
                               -(mod(i - 1, 8))), 1);
end

cfg = lrwpanHRPConfig(Mode='802.15.4a', MeanPRF=mean_prf_mhz, ...
    DataRate=data_rate_mbps, PreambleDuration=preamble_symbols, ...
    CodeIndex=code_index, SamplesPerPulse=samples_per_pulse, ...
    PSDULength=psdu_bytes);
if abs(cfg.SampleRate - fs) > 1
    error('generate_uwb_comm_sample:SampleRate', ...
        'MATLAB generated %.3f MHz instead of %.3f MHz.', ...
        cfg.SampleRate / 1e6, fs / 1e6);
end

[packet, ~] = lrwpanWaveformGenerator(bits, cfg);
packet = complex(packet(:), zeros(numel(packet), 1));
p = max(abs(packet));
if p <= 0 || ~isfinite(p)
    error('generate_uwb_comm_sample:EmptyWaveform', ...
        'The generated comm waveform has no finite nonzero samples.');
end
packet = packet * (peak_amplitude / p);

%% Write CF32 interleaved (I0 Q0 I1 Q1 ...).
outdir = fileparts(mfilename('fullpath'));
cf32 = fullfile(outdir, ...
    sprintf('uwb_code%d_preamble%d_payload%d.cfile', ...
            code_index, preamble_symbols, psdu_bytes));
inter = zeros(2 * numel(packet), 1);
inter(1:2:end) = real(packet);
inter(2:2:end) = imag(packet);
fid = fopen(cf32, 'wb');
if fid < 0
    error('generate_uwb_comm_sample:OpenFailed', 'cannot open %s', cf32);
end
fwrite(fid, inter, 'float32');
fclose(fid);
fprintf('Wrote %s : %d samples = %.3f us\n', ...
        cf32, numel(packet), numel(packet) / fs * 1e6);
